services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest-lite
    hostname: oracle-db
    ports:
      - 1521:1521
    environment:
      - ORACLE_PASSWORD=A_rD5tr0ng_PwsD_2025!
    # healthcheck:
    #   test: ["CMD", "/usr/bin/healthcheck"]
    #   start_period: 3m
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - ords-net

  ords:
    container_name: ords
    networks:
      - ords-net
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        # condition: service_healthy
        condition: service_started
    environment:
      - DB_HOSTNAME=oracle-db
      - DB_PORT=1521
      - DB_SERVICE=FREEPDB1
      - DB_PASSWORD=A_rD5tr0ng_PwsD_2025!
      - ORDS_PUBLIC_PASSWORD=A_rD5tr0ng_PwsD_2025!
    volumes:
      - ords_config:/opt/ords_config
    build: backend/ords
    restart: unless-stopped

  # backend:
  #   build: backend

networks:
  ords-net:
    driver: bridge

volumes:
  oracle_data:
  ords_config:
