CREATE TABLE IF NOT EXISTS recipe (
  recipe_id INT GENERATED BY DEFAULT AS IDENTITY,
  recipe_name VARCHAR2(600),
  recipe_instructions CLOB,
  PRIMARY KEY (recipe_id)
  );

CREATE TABLE IF NOT EXISTS ingredient (
  ingredient_id INT GENERATED BY DEFAULT AS IDENTITY,
  ingredient_name VARCHAR(200),
  ingredient_type VARCHAR(1000),
  PRIMARY KEY (ingredient_id)
  );

CREATE TABLE IF NOT EXISTS recipe_ingredients (
  recipe_id INT,
  ingredient_id INT,
  amount DECIMAL (10, 2),
  unit VARCHAR (50),
  PRIMARY KEY (recipe_id, ingredient_id),
  FOREIGN KEY (recipe_id)
  REFERENCES recipe (recipe_id),
  FOREIGN KEY (ingredient_id)
  REFERENCES ingredient (ingredient_id)
  );

CREATE TABLE IF NOT EXISTS course (
  course_id INT GENERATED BY DEFAULT AS IDENTITY,
  course_name VARCHAR(400),
  course_theme VARCHAR(100),
  course_online BOOLEAN,
  course_difficulty VARCHAR(100),
  PRIMARY KEY (course_id)
  );

CREATE TABLE IF NOT EXISTS course_dates (
  date_id INT,
  course_id INT,
  course_date DATE,
  PRIMARY KEY (date_id),
  FOREIGN KEY (course_id)
  REFERENCES course (course_id)
  );

CREATE TABLE IF NOT EXISTS course_recipes (
  course_id INT,
  recipe_id INT,
  PRIMARY KEY (course_id, recipe_id),
  FOREIGN KEY (course_id)
  REFERENCES course (course_id),
  FOREIGN KEY (recipe_id)
  REFERENCES recipe (recipe_id)
  );

CREATE TABLE IF NOT EXISTS user (
  user_id INT,
  user_username VARCHAR (50),
  user_name VARCHAR (100),
  user_firstname VARCHAR (100),
  user_password VARCHAR(200),
  user_admin BOOLEAN,
  PRIMARY KEY (user_id)
  );

CREATE TABLE IF NOT EXISTS role (
  role_id INT,
  role_name VARCHAR (50)
  PRIMARY KEY (role_id)
  );

CREATE TABLE IF NOT EXISTS user_roles (
  user_id INT,
  role_id INT,
  PRIMARY KEY (user_id, role_id),
  FOREIGN KEY (user_id)
  REFERENCES user (user_id),
  FOREIGN KEY (role_id)
  REFERENCES role (role_id)
  );

CREATE TABLE IF NOT EXISTS user_courses (
  user_id INT,
  course_id INT,
  course_status VARCHAR (50),
  PRIMARY KEY (user_id, course_id),
  FOREIGN KEY (user_id)
  REFERENCES user (participant_id),
  FOREIGN KEY (course_id)
  REFERENCES course (course_id)
  );

CREATE TABLE IF NOT EXISTS user_course_progress (
  user_id INT,
  date_id INT,
  is_completed BOOLEAN,
  PRIMARY KEY (user_id, date_id),
  FOREIGN KEY (user_id)
  REFERENCES user (user_id),
  FOREIGN KEY (date_id)
  REFERENCES course_dates (date_id)
  );
